import {AnySchemaObject} from './AnySchemaObject';
import {Reference} from './Reference';
import {Server} from './Server';
import {Channel} from './Channel';
import {ServerVariable} from './ServerVariable';
import {Operation} from './Operation';
import {MessageObject} from './MessageObject';
import {UserPassword} from './UserPassword';
import {ApiKey} from './ApiKey';
import {X509} from './X509';
import {SymmetricEncryption} from './SymmetricEncryption';
import {AsymmetricEncryption} from './AsymmetricEncryption';
import {BearerHttpSecurityScheme} from './BearerHttpSecurityScheme';
import {ApiKeyHttpSecurityScheme} from './ApiKeyHttpSecurityScheme';
import {Oauth2Flows} from './Oauth2Flows';
import {OpenIdConnect} from './OpenIdConnect';
import {SaslPlainSecurityScheme} from './SaslPlainSecurityScheme';
import {SaslScramSecurityScheme} from './SaslScramSecurityScheme';
import {SaslGssapiSecurityScheme} from './SaslGssapiSecurityScheme';
import {Parameter} from './Parameter';
import {CorrelationId} from './CorrelationId';
import {OperationTrait} from './OperationTrait';
import {MessageTrait} from './MessageTrait';
import {OperationReply} from './OperationReply';
import {OperationReplyAddress} from './OperationReplyAddress';
import {ServerBindingsObject} from './ServerBindingsObject';
import {ChannelBindingsObject} from './ChannelBindingsObject';
import {OperationBindingsObject} from './OperationBindingsObject';
import {MessageBindingsObject} from './MessageBindingsObject';
import {Tag} from './Tag';
import {ExternalDocs} from './ExternalDocs';
interface Components {
  'schemas'?: Map<string, any | AnySchemaObject | boolean>;
  'servers'?: Map<string, any | Reference | Server>;
  'channels'?: Map<string, any | Reference | Channel>;
  'serverVariables'?: Map<string, any | Reference | ServerVariable>;
  'operations'?: Map<string, any | Reference | Operation>;
  'messages'?: Map<string, any | Reference | MessageObject>;
  'securitySchemes'?: Map<string, any | Reference | UserPassword | ApiKey | X509 | SymmetricEncryption | AsymmetricEncryption | any | BearerHttpSecurityScheme | ApiKeyHttpSecurityScheme | Oauth2Flows | OpenIdConnect | SaslPlainSecurityScheme | SaslScramSecurityScheme | SaslGssapiSecurityScheme>;
  'parameters'?: Map<string, any | Reference | Parameter>;
  'correlationIds'?: Map<string, any | Reference | CorrelationId>;
  'operationTraits'?: Map<string, any | Reference | OperationTrait>;
  'messageTraits'?: Map<string, any | Reference | MessageTrait>;
  'replies'?: Map<string, any | Reference | OperationReply>;
  'replyAddresses'?: Map<string, any | Reference | OperationReplyAddress>;
  'serverBindings'?: Map<string, any | Reference | ServerBindingsObject>;
  'channelBindings'?: Map<string, any | Reference | ChannelBindingsObject>;
  'operationBindings'?: Map<string, any | Reference | OperationBindingsObject>;
  'messageBindings'?: Map<string, any | Reference | MessageBindingsObject>;
  'tags'?: Map<string, any | Reference | Tag>;
  'externalDocs'?: Map<string, any | Reference | ExternalDocs>;
  'additionalProperties'?: Map<string, any>;
}
export { Components };