import {CoreSchemaMetaMinusSchemaObject} from './CoreSchemaMetaMinusSchemaObject';
import {AnySchemaObject} from './AnySchemaObject';
import {JsonMinusSchemaMinusDraftMinus_07MinusSchemaSimpleTypes} from './JsonMinusSchemaMinusDraftMinus_07MinusSchemaSimpleTypes';
import {Reference} from './Reference';
import {ExternalDocs} from './ExternalDocs';
interface SchemaObject {
  '$id'?: string;
  '$schema'?: string;
  '$ref'?: string;
  '$comment'?: string;
  'title'?: string;
  'description'?: string;
  'default'?: any;
  'readOnly'?: boolean;
  'writeOnly'?: boolean;
  'examples'?: any[];
  'multipleOf'?: number;
  'maximum'?: number;
  'exclusiveMaximum'?: number;
  'minimum'?: number;
  'exclusiveMinimum'?: number;
  'maxLength'?: number;
  'minLength'?: number;
  'pattern'?: string;
  'additionalItems'?: CoreSchemaMetaMinusSchemaObject | boolean;
  'items'?: any | (AnySchemaObject | boolean)[];
  'maxItems'?: number;
  'minItems'?: number;
  'uniqueItems'?: boolean;
  'contains'?: AnySchemaObject | boolean;
  'maxProperties'?: number;
  'minProperties'?: number;
  'required'?: string[];
  'additionalProperties'?: CoreSchemaMetaMinusSchemaObject | boolean;
  'definitions'?: Map<string, AnySchemaObject | boolean>;
  'properties'?: Map<string, AnySchemaObject | boolean>;
  'patternProperties'?: Map<string, AnySchemaObject | boolean>;
  'dependencies'?: Map<string, any | string[]>;
  'propertyNames'?: AnySchemaObject | boolean;
  'const'?: any;
  'enum'?: any[];
  'type'?: JsonMinusSchemaMinusDraftMinus_07MinusSchemaSimpleTypes | JsonMinusSchemaMinusDraftMinus_07MinusSchemaSimpleTypes[];
  'format'?: string;
  'contentMediaType'?: string;
  'contentEncoding'?: string;
  'if'?: CoreSchemaMetaMinusSchemaObject | boolean;
  'then'?: CoreSchemaMetaMinusSchemaObject | boolean;
  'else'?: CoreSchemaMetaMinusSchemaObject | boolean;
  'allOf'?: (AnySchemaObject | boolean)[];
  'anyOf'?: (AnySchemaObject | boolean)[];
  'oneOf'?: (AnySchemaObject | boolean)[];
  'not'?: AnySchemaObject | boolean;
  'discriminator'?: string;
  'externalDocs'?: Reference | ExternalDocs;
  'deprecated'?: boolean;
  'reserved_additionalProperties'?: Map<string, any | any>;
}
export { SchemaObject };