import {Reference} from './Reference';
import {ServerVariable} from './ServerVariable';
import {UserPassword} from './UserPassword';
import {ApiKey} from './ApiKey';
import {X509} from './X509';
import {SymmetricEncryption} from './SymmetricEncryption';
import {AsymmetricEncryption} from './AsymmetricEncryption';
import {BearerHttpSecurityScheme} from './BearerHttpSecurityScheme';
import {ApiKeyHttpSecurityScheme} from './ApiKeyHttpSecurityScheme';
import {Oauth2Flows} from './Oauth2Flows';
import {OpenIdConnect} from './OpenIdConnect';
import {SaslPlainSecurityScheme} from './SaslPlainSecurityScheme';
import {SaslScramSecurityScheme} from './SaslScramSecurityScheme';
import {SaslGssapiSecurityScheme} from './SaslGssapiSecurityScheme';
import {Tag} from './Tag';
import {ExternalDocs} from './ExternalDocs';
import {ServerBindingsObject} from './ServerBindingsObject';
interface Server {
  'host': string;
  'pathname'?: string;
  'title'?: string;
  'summary'?: string;
  'description'?: string;
  'protocol': string;
  'protocolVersion'?: string;
  'variables'?: Map<string, Reference | ServerVariable>;
  'security'?: (Reference | UserPassword | ApiKey | X509 | SymmetricEncryption | AsymmetricEncryption | any | BearerHttpSecurityScheme | ApiKeyHttpSecurityScheme | Oauth2Flows | OpenIdConnect | SaslPlainSecurityScheme | SaslScramSecurityScheme | SaslGssapiSecurityScheme)[];
  'tags'?: (Reference | Tag)[];
  'externalDocs'?: Reference | ExternalDocs;
  'bindings'?: Reference | ServerBindingsObject;
  'additionalProperties'?: Map<string, any>;
}
export { Server };