import {ChannelBindingsObjectWs} from './ChannelBindingsObjectWs';
import {ChannelBindingsObjectAmqp} from './ChannelBindingsObjectAmqp';
import {ChannelBindingsObjectKafka} from './ChannelBindingsObjectKafka';
import {ChannelBindingsObjectAnypointmq} from './ChannelBindingsObjectAnypointmq';
import {ChannelBindingsObjectJms} from './ChannelBindingsObjectJms';
import {ChannelBindingsObjectSns} from './ChannelBindingsObjectSns';
import {ChannelBindingsObjectSqs} from './ChannelBindingsObjectSqs';
import {ChannelBindingsObjectIbmmq} from './ChannelBindingsObjectIbmmq';
import {ChannelBindingsObjectGooglepubsub} from './ChannelBindingsObjectGooglepubsub';
import {ChannelBindingsObjectPulsar} from './ChannelBindingsObjectPulsar';
interface ChannelBindingsObject {
  'http'?: any;
  'ws'?: ChannelBindingsObjectWs;
  'amqp'?: ChannelBindingsObjectAmqp;
  'amqp1'?: any;
  'mqtt'?: any;
  'kafka'?: ChannelBindingsObjectKafka;
  'anypointmq'?: ChannelBindingsObjectAnypointmq;
  'nats'?: any;
  'jms'?: ChannelBindingsObjectJms;
  'sns'?: ChannelBindingsObjectSns;
  'sqs'?: ChannelBindingsObjectSqs;
  'stomp'?: any;
  'redis'?: any;
  'ibmmq'?: ChannelBindingsObjectIbmmq;
  'solace'?: any;
  'googlepubsub'?: ChannelBindingsObjectGooglepubsub;
  'pulsar'?: ChannelBindingsObjectPulsar;
  'additionalProperties'?: Map<string, any>;
}
export { ChannelBindingsObject };